import { z } from 'zod';

export const rewardsRuntimeConfigSchema = z.object({
  enabled: z.boolean(),
  scannerLimit: z.number().int().positive(),
  candidateLimit: z.number().int().positive(),
  quoteOffset: z.number().nonnegative(),
  minDailyReward: z.number().nonnegative(),
  minSecondsToClose: z.number().int().nonnegative(),
  maxGlobalNotional: z.number().positive(),
  maxMarketNotional: z.number().positive(),
  maxOpenMarkets: z.number().int().positive(),
  maxMidpointDrift: z.number().nonnegative(),
  maxOrderAgeSeconds: z.number().int().positive(),
  maxOrderHardAgeSeconds: z.number().int().positive(),
  maxOrderbookAgeSeconds: z.number().positive(),
  maxInventorySharesPerOutcome: z.number().nonnegative(),
  inventoryExitEnabled: z.boolean(),
  maxUnhedgedInventoryAgeSeconds: z.number().int().positive(),
  maxInventoryLossPerShare: z.number().nonnegative(),
  minInventoryExitShares: z.number().nonnegative(),
  minCollateralBalance: z.number().nonnegative(),
  maxActiveOrdersPerMarket: z.number().int().positive(),
  blockedCategories: z.array(z.string()),
  blockedKeywords: z.array(z.string()),
});
